### ISSUE TITLE
Marantz remote control

### ISSUE THREAD

**Issue by jekkos** [morphar/remotepi#1]
Hi, glad that I found this project, I have been looking to control my Marantz receiver from Kodi since some time.

I wanted to do this using Lirc directly by capturing the remote control code using a TSOP receiver and then send the code back out again using  ˘irsend`. Up to now I have onty been able to use the marantz remove with Kodi. 

* Did you use any specific hardware to hook the reciever to the raspberry pi? Do you know if the RC input is for an open collector ? I did find some schematics that were built to receive codes back from the amplifier. The signal is at 5V in that case and a level shifter is required. 
* On other forums I read that the Marantz RC signal is active high. and that the signalling might need to be inverted. Any idea if this is correct?
* When I hook up the remote in port on the reciever, it does stop responding to the remote control itself. So in that case, it only responds to what the raspberry pi sends it. I wonder if you are using the remote control or not? As it seems that the functionality that was added does not replace usage of a remote control at first sight.

Perhaps I will just try to cross compile the example here on my host, link it statically and then check if I can run it on the device.

**Comment by morphar** [comment]
Hi @jekkos :)

Great that it's not just me, that can use the code :-D

The only "hardware" I have is 2 wires, one of them with a small resistor (100ohm?).
The RC port is built to be "high", but I coded it, so that it's only open/connected, when it needs to send a signal - this means that the remote still works.

I don't know about the need for inversion and honestly I can't remember anything about this project... :)
But it runs on my Pi, which has moOde running.
It rarely fails (maybe once in 100-200) and when it does, it seems to due to high load on the CPU, which could cause the program to not get exact timings, which in turn causes the rc signal to be wrong - a reboot always helps.

Have you tried it yet?

**Comment by jekkos** [comment]
I have compiled it and it works! this is great. But still my receiver stops responding to the remote once I connect the RC-in. According to the manual, there should be a way to enable the remote again, but it does not seem to work at first sight.

**Comment by jekkos** [comment]
> I have compiled it and [it works](https://sourceforge.net/p/lirc/mailman/lirc-list/thread/5109AC3D.2020003%40perrache.com/)! this is great. But still my receiver stops responding to the remote once I connect the RC-in. According to the manual, there should be a way to enable the remote again, but it does not seem to work at first sight.

**Comment by morphar** [comment]
Great! Nice to hear :)
Do you have a resistor on the RC wire? I can't remember how I got it working, but I do remember, that the trick is to make the receiver think, that there is no signal on the RC-in.
Basically, the RC-in will normally have some box, that has a constant signal, which makes the remote control not work.
But with this code, it should act as if it "connects" the wire, then sends a signal, then disconnects the wire.
The receiver will not see the RC-in cable, if there is no signal through it.
As far as I remember, this only works, when you have a resistor on the wire, just like you would have, when lighting up an LED.
This is a picture (sorry for the quality) of my pi with an iqaudio board and the 2 RC-in wires. The green one is cut to get a 100 ohm resistor in.
![piremote](https://github.com/morphar/remotepi/assets/189420/4776d549-8516-4181-9d3e-913c244ba29c)

Hope this helps.
If not: are you completely sure, that there is nothing generating a signal on the wire?
It should be possible to plug a cable into the RC-in port, without plugging the other end into anything, without losing the ability to use the remote control.

**Comment by morphar** [comment]
Just came to think of this:
I think the trick is to NOT disable the remote control signal.
Have you tried that?

**Comment by jekkos** [comment]
thanks for the suggestions, I have tried indeed to enable the remote control on the Marantz itself but for some reason, this does not work. This can be done by pressing the speaker A or B button for 5s. Then I see the mute LED flashing three or 1 times as described in the manual. The behavior does not change after both actions.

If I change the rpi pin to an input (high impedance) when it does not send a signal then the receiver might consider that as nothing connected.. in the code it looks like the output is set to low and so some signal will probably be present, even when it's not sending anything. I'll try the resistor as well

**Comment by morphar** [comment]
I have just verified, I have the remote control enabled and I'm running the code exactly as it is in this repo.
I'm running an IQAudio HAT and have an original display connected.

The code doesn't change the pin initially, which means it should be low (0V).
This should cause the amplifier to see nothing.
Then when it sends a signal, the remote control probably won't work for that short second or so, due to the pin being high (3.3V).

I think the resistor might be the answer - as you say, there's probably a small amount of noise.

I hope you get it working!
It's such a bliss to hear the amplifier turn itself on and off :)

**Comment by morphar** [comment]
BTW: Is the receiver a PM6007?

**Comment by jekkos** [comment]
Yes having this automated will relieve me from having to find the remote every time I want to play some music on the setup.  I'll see if I can test this tonight with the resistor first. Then my setup will be identical to yours.
You do run the program as a daemon I suppose? I plan to start it using systemd.
The receiver is a PM6005, so it's quite similar.

**Comment by morphar** [comment]
👍
As far as I remember, i run it with systemd as well...
It starts when the system is rebooted, so it must be systemd :)

**Comment by jekkos** [comment]
tried and it's fully working now, have made a small PR (see #2 )

**Comment by morphar** [comment]
Perfect! It has been merged :)
